pipeline {
    agent any
    stages {
        stage('---clean---') {
            steps {
              echo "mvn clean"
            }
        }
        stage('--test--') {
            steps {
                apt update
            }
        }
        stage('--package--') {
            steps {
#                sh "mvn package"
            }
        }
    }
}
